openapi: 3.0.3
info:
  title: API d'accès aux postes
  version: 1.0.0
  description: API permettant de créer et de consulter des postes dans MongoDB.
servers:
  - url: http://localhost:8080
paths:
  /posts:
    get:
      operationId: listPosts
      tags:
        - Posts
      summary: Récupère la liste des postes.
      responses:
        '200':
          description: Liste des postes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      operationId: createPost
      tags:
        - Posts
      summary: Crée un nouveau poste.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostRequest'
      responses:
        '201':
          description: Poste créé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Requête invalide.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /posts/{postId}:
    get:
      operationId: getPost
      tags:
        - Posts
      summary: Récupère un poste via son identifiant.
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
          description: Identifiant du poste recherché.
      responses:
        '200':
          description: Poste trouvé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Poste introuvable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Post:
      type: object
      required:
        - id
        - title
        - summary
        - sourceUrl
        - tags
        - createdAt
        - likes
        - comments
      properties:
        id:
          type: string
          description: Identifiant unique du poste.
        title:
          type: string
          description: Titre du poste.
          minLength: 1
        summary:
          type: string
          description: Résumé court du poste.
          minLength: 1
        sourceUrl:
          type: string
          format: uri
          description: Lien vers la source d'origine.
        tags:
          type: array
          description: Liste des étiquettes associées au poste.
          items:
            type: string
        createdAt:
          type: string
          format: date-time
          description: Date de création du poste.
        likes:
          type: integer
          format: int32
          minimum: 0
          description: Nombre de mentions « j'aime ».
        comments:
          type: array
          description: Commentaires associés au poste.
          items:
            $ref: '#/components/schemas/PostComment'
        viewerHasLiked:
          type: boolean
          nullable: true
          description: Indique si l'utilisateur courant a déjà aimé le poste.
    PostComment:
      type: object
      required:
        - id
        - section
        - author
        - content
        - createdAt
        - replies
      properties:
        id:
          type: string
          description: Identifiant du commentaire.
        section:
          $ref: '#/components/schemas/PostCommentSection'
        author:
          type: string
          description: Nom complet de l'auteur du commentaire.
        authorId:
          type: string
          nullable: true
          description: Identifiant interne de l'auteur du commentaire.
        content:
          type: string
          description: Contenu du commentaire.
        createdAt:
          type: string
          format: date-time
          description: Date de création du commentaire.
        replies:
          type: array
          description: Réponses associées au commentaire.
          items:
            $ref: '#/components/schemas/PostCommentReply'
    PostCommentReply:
      type: object
      required:
        - id
        - parentId
        - author
        - content
        - createdAt
      properties:
        id:
          type: string
          description: Identifiant de la réponse.
        parentId:
          type: string
          description: Identifiant du commentaire parent.
        author:
          type: string
          description: Nom complet de l'auteur de la réponse.
        authorId:
          type: string
          nullable: true
          description: Identifiant interne de l'auteur de la réponse.
        content:
          type: string
          description: Contenu de la réponse.
        createdAt:
          type: string
          format: date-time
          description: Date de création de la réponse.
    PostCommentSection:
      type: string
      description: Section du débat à laquelle se rattache le commentaire.
      enum:
        - analysis
        - debate
        - question
        - proposal
        - avis
    CreatePostRequest:
      type: object
      required:
        - title
        - summary
        - sourceUrl
      properties:
        title:
          type: string
          description: Titre du poste.
          minLength: 1
        summary:
          type: string
          description: Résumé court du poste.
          minLength: 1
        sourceUrl:
          type: string
          format: uri
          description: Lien vers la source d'origine.
        tags:
          type: array
          description: Liste des étiquettes associées au poste.
          items:
            type: string
          default: []
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Code de l'erreur.
        message:
          type: string
          description: Description de l'erreur.
