openapi: 3.0.3
info:
  title: Agora Database Access API
  version: 1.0.0
  description: This API provides access to the Agora database.

servers:
  - url: http://localhost:8080

paths:
  /posts:
    get:
      operationId: listPosts
      tags:
        - Posts
      summary: Retrieves the list of posts.
      responses:
        '200':
          description: List of posts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      operationId: createPost
      tags:
        - Posts
      summary: Creates a new post.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostRequest'
      responses:
        '201':
          description: Post created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /posts/{postId}:
    get:
      operationId: getPost
      tags:
        - Posts
      summary: Retrieves a post by its identifier.
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
          description: Identifier of the requested post.
      responses:
        '200':
          description: Post found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Post:
      type: object
      required:
        - id
        - title
        - summary
        - sourceUrl
        - tags
        - createdAt
        - likes
        - comments
      properties:
        id:
          type: string
          description: Unique identifier of the post.
        title:
          type: string
          description: Title of the post.
          minLength: 1
        summary:
          type: string
          description: Short summary of the post.
          minLength: 1
        sourceUrl:
          type: string
          format: uri
          description: Link to the original source.
        tags:
          type: array
          description: List of tags associated with the post.
          items:
            type: string
        createdAt:
          type: string
          format: date-time
          description: Post creation date.
        likedBy:
          type: array
          description: List of user identifiers who liked the post.
          items:
            type: string
        comments:
          type: array
          description: Comments associated with the post.
          items:
            $ref: '#/components/schemas/PostComment'
    PostComment:
      type: object
      required:
        - id
        - section
        - authorName
        - authorId
        - content
        - createdAt
        - replies
      properties:
        id:
          type: string
          description: Comment identifier.
        section:
          $ref: '#/components/schemas/PostCommentSection'
        authorName:
          type: string
          description: Full name of the comment author.
        authorId:
          type: string
          description: Internal identifier of the comment author.
        content:
          type: string
          description: Comment content.
        createdAt:
          type: string
          format: date-time
          description: Comment creation date.
        replies:
          type: array
          description: Replies associated with the comment.
          items:
            $ref: '#/components/schemas/PostCommentReply'
    PostCommentReply:
      type: object
      required:
        - id
        - parentId
        - authorName
        - authorId
        - content
        - createdAt
      properties:
        id:
          type: string
          description: Reply identifier.
        parentId:
          type: string
          description: Identifier of the parent comment.
        authorName:
          type: string
          description: Full name of the reply author.
        authorId:
          type: string
          description: Internal identifier of the reply author.
        content:
          type: string
          description: Reply content.
        createdAt:
          type: string
          format: date-time
          description: Reply creation date.
    PostCommentSection:
      type: string
      description: Debate section to which the comment belongs.
      enum:
        - analysis
        - debate
        - question
        - proposal
        - avis
    CreatePostRequest:
      type: object
      required:
        - title
        - summary
        - sourceUrl
        - tags
      properties:
        title:
          type: string
          description: Post title.
          minLength: 1
        summary:
          type: string
          description: Short summary of the post.
          minLength: 1
        sourceUrl:
          type: string
          format: uri
          description: Link to the original source.
        tags:
          type: array
          description: List of tags associated with the post.
          items:
            type: string
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error description.